program: param_sweep.py
method: bayes
metric:
  name: eval_loss
  goal: minimize
parameters:
  learning_rate:
    distribution: uniform
    min: 5e-5
    max: 1e-3
  batch_size:
    values: [8, 16]
  num_epochs:
    values: [3, 10, 20]
  lora_r:
    values: [8, 16, 32]
  lora_alpha:
    values: [16, 32, 64]
  lora_dropout:
    values: [0.05, 0.1]